name: Update GitHub Stats in README

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:     # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get GitHub stats
        id: get_stats
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = 'SirJohnGabriel';
            const user = await github.rest.users.getByUsername({ username });

            const repos = await github.paginate(github.rest.repos.listForUser, {
              username,
              per_page: 100,
            });

            const stars = repos.reduce((sum, repo) => sum + repo.stargazers_count, 0);

            const events = await github.paginate(github.rest.activity.listPublicEventsForUser, {
              username,
              per_page: 100,
            });

            const commits = events
              .filter(e => e.type === 'PushEvent')
              .reduce((acc, e) => acc + e.payload.commits.length, 0);

            const pulls = await github.paginate(github.rest.search.issuesAndPullRequests, {
              q: `author:${username} is:pr`,
              per_page: 100,
            });

            core.setOutput('stars', stars);
            core.setOutput('commits', commits);
            core.setOutput('prs', pulls.total_count);

      - name: Replace placeholders in README
        run: |
          COMMITS=${{ steps.get_stats.outputs.commits }}
          PRS=${{ steps.get_stats.outputs.prs }}
          STARS=${{ steps.get_stats.outputs.stars }}

          sed -i "s/<!--COMMIT_COUNT-->.*/$COMMITS/" README.md
          sed -i "s/<!--PR_COUNT-->.*/$PRS/" README.md
          sed -i "s/<!--STAR_COUNT-->.*/$STARS/" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "⬆️ Update GitHub stats"
          git push
